version: '3'

services:
  supabase:
    image: supabase/supabase-dev:latest
    ports:
      - '8000:8000'
    environment:
      DB_HOST: db
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_PORT: 5432
      DB_SCHEMA: public
    depends_on:
      - db
  db:
    image: supabase/postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: postgres
